
default-keys: ["1234"]

agent-metrics: true

droplets:
  keys: ["123"]
  url: "https://api.digitalocean.com/v2/droplets"
  interval: 1h
  metrics:
    - memory
    - vcpu
    - disk
    - status

metrics:
  base-url: "https://api.digitalocean.com/v2/monitoring/metrics/droplet"
  bandwidth:
    types: [ private_inbound, private_outbound, public_inbound, public_outbound ]
    keys: ["123"]
    interval: 10s
    enabled: true
  cpu:
    keys: ["123"]
    interval: 15s
    enabled: true
  filesystem:
    types: [ free, size ]
    keys: ["123"]
    interval: 60s
    enabled: true
  memory:
    types: [ cached, free, total, available ]
    keys: ["123"]
    interval: 10s
    enabled: true
  load:
    types: [ load_1, load_5, load_15 ]
    keys: ["123"]
    interval: 10s
    enabled: true





