

default_key: "1234"

droplets-basic:
  key: "123"
  interval: 1h

metrics:
  bandwidth:
    key: "123"
    interval: 10s
    enabled: true
  cpu:
    key: "123"
    interval: 10s
    enabled: true
  filesystem_free:
    key: "123"
    interval: 10s
    enabled: true
  filesystem_size:
    key: "123"
    interval: 10s
    enabled: true
  memory_cached:
    key: "123"
    interval: 10s
    enabled: true
  memory_free:
    key: "123"
    interval: 10s
    enabled: true
  memory_total:
    key: "123"
    interval: 10s
    enabled: true
  memory_available:
    key: "123"
    interval: 10s
    enabled: true
  load_1:
    key: "123"
    interval: 10s
    enabled: true
  load_5:
    key: "123"
    interval: 10s
    enabled: true
  load_15:
    key: "123"
    interval: 10s
    enabled: true





