{
 "title": "Droplets Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "droplets",
    "query": {
     "query": "label_values(droxporter_droplet_memory_settings, droplet)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Max CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(1 - (avg(rate(droxporter_droplet_cpu{mode=\"idle\", droplet=~\"$droplets\"}[5m])) by (droplet) / sum(rate(droxporter_droplet_cpu{droplet=~\"$droplets\"}[5m])) by (droplet)))",
     "legendFormat": "{{droplet}}"
    }
   ]
  },
  {
   "title": "Max Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(1 - (droxporter_droplet_memory {metric_type=\"available\", droplet=~\"$droplets\"} / on (droplet) droxporter_droplet_memory {metric_type=\"total\", droplet=~\"$droplets\"}))",
     "legendFormat": "{{droplet}} "
    }
   ]
  },
  {
   "title": "Max Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(droxporter_droplet_memory {metric_type=\"total\", droplet=~\"$droplets\"} - on (droplet)  (droxporter_droplet_memory {metric_type=\"available\", droplet=~\"$droplets\"}  ))",
     "legendFormat": "{{droplet}} "
    }
   ]
  },
  {
   "title": "Total External Outbound Network Bandwith",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "\r\n\r\nsum(droxporter_droplet_bandwidth{interface=\"public\", direction=\"outbound\", droplet =~ \"$droplets\"}[$__interval]) * $__interval_ms / 1000 / 8",
     "legendFormat": "{{droplet}} {{direction}}"
    }
   ]
  },
  {
   "title": "Total Droplets Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(droxporter_droplet_memory_settings {droplet=~\"$droplets\"})",
     "legendFormat": "{{droplet}}"
    }
   ]
  },
  {
   "title": "Total Droplets CPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(droxporter_droplet_vcpu_settings {droplet=~\"$droplets\"})",
     "legendFormat": "{{droplet}}"
    }
   ]
  },
  {
   "title": "Droplets Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (droplet) (droxporter_droplet_memory_settings {droplet=~\"$droplets\"}))",
     "legendFormat": "{{droplet}}"
    }
   ]
  },
  {
   "title": "Droplets Disk Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(droxporter_droplet_disk_settings {droplet=~\"$droplets\"})",
     "legendFormat": "{{droplet}}"
    }
   ]
  },
  {
   "title": "Max Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(1 - (droxporter_droplet_filesystem { metric_type=\"free\" , droplet=~\"$droplets\"} / on (droplet) droxporter_droplet_disk_settings {droplet=~\"$droplets\"} / 1024  / 1024 / 1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(droxporter_droplet_disk_settings {droplet=~\"$droplets\"} * 1024  * 1024 * 1024 ) - sum(droxporter_droplet_filesystem { metric_type=\"free\", droplet=~\"$droplets\" } )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Free Disk Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "min(droxporter_droplet_filesystem { metric_type=\"free\", droplet=~\"$droplets\" } )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total External Inbound Network Bandwith",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "\r\n\r\nsum(droxporter_droplet_bandwidth{interface=\"public\", direction=\"inbound\", droplet =~ \"$droplets\"}[$__interval]) * $__interval_ms / 1000 / 8",
     "legendFormat": "{{droplet}} {{direction}}"
    }
   ]
  },
  {
   "title": "Droplets Settings",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(droxporter_droplet_memory_settings {droplet=~\"$droplets\"}) by (droplet) ",
     "legendFormat": "{{droplet}}"
    },
    {
     "expr": "max(droxporter_droplet_vcpu_settings{droplet=~\"$droplets\"}) by (droplet) ",
     "legendFormat": "{{droplet}}"
    },
    {
     "expr": "max(droxporter_droplet_disk_settings{droplet=~\"$droplets\"}) by (droplet) ",
     "legendFormat": "{{droplet}}"
    },
    {
     "expr": "sum(droxporter_droplet_disk_settings {droplet=~\"$droplets\"} * 1024  * 1024 * 1024 ) by (droplet)  - sum(droxporter_droplet_filesystem { metric_type=\"free\", droplet=~\"$droplets\" } ) by (droplet) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(droxporter_droplet_memory {metric_type=\"total\", droplet=~\"$droplets\"} - on (droplet)  (droxporter_droplet_memory {metric_type=\"available\", droplet=~\"$droplets\"}  )) by (droplet) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (avg(rate(droxporter_droplet_cpu{mode=\"idle\", droplet=~\"$droplets\"}[5m])) by (droplet) / sum(rate(droxporter_droplet_cpu{droplet=~\"$droplets\"}[5m])) by (droplet))",
     "legendFormat": "{{droplet}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (droxporter_droplet_memory {metric_type=\"available\", droplet=~\"$droplets\"} / on (droplet) droxporter_droplet_memory {metric_type=\"total\", droplet=~\"$droplets\"})",
     "legendFormat": "{{droplet}} "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (droxporter_droplet_filesystem { metric_type=\"free\", droplet=~\"$droplets\" } / on (droplet) droxporter_droplet_disk_settings {droplet=~\"$droplets\"} / 1024  / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public Network Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "max(droxporter_droplet_bandwidth {interface=\"public\", droplet =~ \"$droplets\"}[$__interval]) by (droplet, direction)",
     "legendFormat": "{{droplet}} {{direction}}"
    }
   ]
  },
  {
   "title": "Private Network Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "max(droxporter_droplet_bandwidth {interface=\"private\", droplet =~ \"$droplets\"}[$__interval]) by (droplet, direction)",
     "legendFormat": "{{droplet}} {{direction}}"
    }
   ]
  }
 ]
}