{
 "title": "Droxporter Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Max CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "droxporter_self_cpu_usage_percents {}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "droxporter_self_memory_usage {}"
    }
   ]
  },
  {
   "title": "Response Statuses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_digital_ocean_request_counter {}[$__interval]))  by (result) ",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Job Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_jobs_counter {}[$__interval]))",
     "legendFormat": "{{type}} {{result}}"
    }
   ]
  },
  {
   "title": "Job Time Quantile 90%",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(droxporter_jobs_time_histogram_seconds_bucket[$__range])) by (le))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg Requests Per Job",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_digital_ocean_request_counter[$__range])) / sum(increase(droxporter_jobs_counter[$__range]))",
     "legendFormat": "{{type}} {{result}}"
    }
   ]
  },
  {
   "title": "Job Fails",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_jobs_counter {result = \"fail\"}[$__interval]))",
     "legendFormat": "{{type}} {{result}}"
    }
   ]
  },
  {
   "title": "Total Http Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_digital_ocean_request_counter {}[$__interval])) ",
     "legendFormat": "{{type}} {{result}}"
    }
   ]
  },
  {
   "title": "Http Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_digital_ocean_request_counter{})[$__interval]) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Job Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_jobs_counter{})[$__rate_interval]) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Response Time Quantile 90%",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(droxporter_digital_ocean_request_histogram_seconds_bucket[$__range])) by (le))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Http Call Time Quantile 90%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(droxporter_digital_ocean_request_histogram_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Job Execution Time Quantile 90%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(droxporter_jobs_time_histogram_seconds_bucket[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Api Keys Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(droxporter_keys_count_by_status {}) by (key_type, status))",
     "legendFormat": "{{key_type}} {{status}}"
    }
   ]
  },
  {
   "title": "Api Keys Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "max(droxporter_keys_count_by_status {}) by (key_type, status)",
     "legendFormat": "{{key_type}} {{status}}"
    }
   ]
  },
  {
   "title": "Remaining Calls By Rate Limiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 22 },
   "targets": [
    {
     "expr": "max(droxporter_remaining_limits_by_key {} [$__rate_interval]) by (key_type, timeframe)",
     "legendFormat": "{{key_type}}  {{timeframe}}"
    }
   ]
  },
  {
   "title": "Api Key Aquisition Fails",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_keys_errors {})[$__rate_interval]) ",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Api Key Aquisition Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 30 },
   "targets": [
    {
     "expr": "sum(increase(droxporter_keys_errors {})[$__rate_interval]) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Job Runs Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(droxporter_jobs_counter{result = \"fail\"})[$__rate_interval]) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}